#Makefile generated by amake
#On Fri May 29 11:57:56 2020
#To print amake help use 'amake --help'.
CC=gcc
CPPC=g++
LINK=g++
SRCDIR=src
OBJDIR=obj
FLAGS=-g -Wall -std=c++11 -pthread -I/usr/include/ncursesw 
LIBS=-lncursesw 
OBJS=$(OBJDIR)/mhw_lookup.o $(OBJDIR)/main.o $(OBJDIR)/utils.o $(OBJDIR)/ui.o $(OBJDIR)/memory.o $(OBJDIR)/patterns.o 
EXEC=linux-hunter
DATE=$(shell date +"%Y-%m-%d")

$(EXEC) : $(OBJS)
	$(LINK) $(OBJS) -o $(EXEC) $(FLAGS) $(LIBS)

$(OBJDIR)/mhw_lookup.o: src/mhw_lookup.cpp src/mhw_lookup.h src/memory.h \
 src/patterns.h src/ui.h src/timer.h src/mhw_lookup_monster.h \
 src/offsets.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/mhw_lookup.cpp -c -o $@

$(OBJDIR)/main.o: src/main.cpp src/memory.h src/patterns.h src/ui.h src/timer.h \
 src/events.h src/mhw_lookup.h src/utils.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/main.cpp -c -o $@

$(OBJDIR)/utils.o: src/utils.cpp src/utils.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/utils.cpp -c -o $@

$(OBJDIR)/ui.o: src/ui.cpp src/ui.h src/timer.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/ui.cpp -c -o $@

$(OBJDIR)/memory.o: src/memory.cpp src/memory.h src/patterns.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/memory.cpp -c -o $@

$(OBJDIR)/patterns.o: src/patterns.cpp src/patterns.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/patterns.cpp -c -o $@

$(OBJDIR)/__setup_obj_dir :
	mkdir -p $(OBJDIR)
	touch $(OBJDIR)/__setup_obj_dir

.PHONY: clean bzip release

clean :
	rm -rf $(OBJDIR)/*.o
	rm -rf $(EXEC)

bzip :
	tar -cvf "$(DATE).$(EXEC).tar" $(SRCDIR)/* Makefile
	bzip2 "$(DATE).$(EXEC).tar"

release : FLAGS +=-O3 -D_RELEASE
release : $(EXEC)

