#Makefile generated by amake
#On Tue May 26 09:11:19 2020
#To print amake help use 'amake --help'.
CC=gcc
CPPC=g++
LINK=g++
SRCDIR=src
OBJDIR=obj
FLAGS=-g -Wall -std=c++11 -pthread -I/usr/include/ncursesw 
LIBS=-lncursesw 
OBJS=$(OBJDIR)/main.o $(OBJDIR)/ui.o $(OBJDIR)/memory.o $(OBJDIR)/patterns.o 
EXEC=linux-hunter
DATE=$(shell date +"%Y-%m-%d")

$(EXEC) : $(OBJS)
	$(LINK) $(OBJS) -o $(EXEC) $(FLAGS) $(LIBS)

$(OBJDIR)/main.o: src/main.cpp src/patterns.h src/offsets.h src/memory.h src/ui.h \
 src/events.h src/timer.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/main.cpp -c -o $@

$(OBJDIR)/ui.o: src/ui.cpp src/ui.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/ui.cpp -c -o $@

$(OBJDIR)/memory.o: src/memory.cpp src/memory.h src/patterns.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/memory.cpp -c -o $@

$(OBJDIR)/patterns.o: src/patterns.cpp src/patterns.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/patterns.cpp -c -o $@

$(OBJDIR)/__setup_obj_dir :
	mkdir -p $(OBJDIR)
	touch $(OBJDIR)/__setup_obj_dir

.PHONY: clean bzip release

clean :
	rm -rf $(OBJDIR)/*.o
	rm -rf $(EXEC)

bzip :
	tar -cvf "$(DATE).$(EXEC).tar" $(SRCDIR)/* Makefile
	bzip2 "$(DATE).$(EXEC).tar"

release : FLAGS +=-O3 -D_RELEASE
release : $(EXEC)

