#ifndef _MHW_LOOKUP_MONSTER_H_
#define _MHW_LOOKUP_MONSTER_H_

// list taken from https://github.com/sir-wilhelm/SmartHunter/blob/master/SmartHunter/Game/Config/MonsterDataConfig.cs
// cat tmp/SmartHunter/SmartHunter/Game/Config/MonsterDataConfig.cs | grep "\"em" -A1 -B0 | sed -e 's/\"em/{ L\"em/' -e 's/.*MONSTER.*/\L&/' 
// \ -e 's/.*monster.*",/& }/' -e 's/, }/ },/' -e 's/.*monster_/\t\t\"/' | grep -v -- "--"

namespace mhw_lookup {
	struct monster_data {
		const wchar_t	*id;
		const char	*name;
	};

	monster_data	MONSTERS[] = {
                { L"em001_00", // true
		"rathian" },
                { L"em001_01", // true
		"pink_rathian" },
                { L"em001_02", // true
		"gold_rathian" },
                { L"em002_00", // true
		"rathalos" },
                { L"em002_01", // true
		"azure_rathalos" },
                { L"em002_02", // true
		"silver_rathalos" },
                { L"em007_00", // true
		"diablos" },
                { L"em007_01", // true
		"black_diablos" },
                { L"em011_00", // true
		"kirin" },
                { L"em018_00",
		"yian_garuga" },
                { L"em018_05",
		"scarred_yian_garuga" },
                { L"em023_00",
		"rajang" },
                { L"em023_05",
		"furious_rajang" },
                { L"em024_00",
		"kushala_daora" },
                { L"em026_00",
		"lunastra" },
                { L"em027_00",
		"teostra" },
                { L"em032_00",
		"tigrex" },
                { L"em032_01",
		"brute_tigrex" },
                { L"em036_00",
		"lavasioth" },
                { L"em037_00",
		"nargacuga" },
                { L"em042_00",
		"barioth" },
                { L"em043_00",
		"deviljho" },
                { L"em043_05",
		"savage_deviljho" },
                { L"em044_00",
		"barroth" },
                { L"em045_00",
		"uragaan" },
                { L"em057_00",
		"zinogre" },
                { L"em063_00",
		"brachydios" },
                { L"em063_05",
		"raging_brachydios" },
                { L"em057_01",
		"stygian_zinogre" },
                { L"em080_00",
		"glavenus" },
                { L"em080_01",
		"acidic_glavenus" },
                { L"em100_00",
		"anjanath" },
                { L"em100_01",
		"anjanath_fulgur" },
                { L"em101_00",
		"great_jagras" },
                { L"em102_00",
		"pukei_pukei" },
                { L"em102_01",
		"pukei_pukei_coral" },
                { L"em103_00",
		"nergigante" },
                { L"em103_05",
		"ruiner_nergigante" },
                { L"em104_00",
		"safi_jiiva" },
                { L"em105_00",
		"xeno_jiiva" },
                { L"em106_00",
		"zorah_magdaros" },
                { L"em107_00",
		"kulu_ya_ku" },
                { L"em108_00",
		"jyuratodus" },
                { L"em109_00",
		"tobi_kadachi" },
                { L"em109_01",
		"viper_tobi_kadachi" },
                { L"em110_00",
		"paolumu" },
                { L"em110_01",
		"paolumu_nightshade" },
                { L"em111_00",
		"legiana" },
                { L"em111_05",
		"shrieking_legiana" },
                { L"em112_00",
		"great_girros" },
                { L"em113_00",
		"odogaron" },
                { L"em113_01",
		"ebony_odogaron" },
                { L"em114_00",
		"radobaan" },
                { L"em115_00",
		"vaal_hazak" },
                { L"em115_05",
		"blackveil_vaal_hazak" },
                { L"em116_00",
		"dodogama" },
                { L"em117_00",
		"kulve_taroth" },
                { L"em118_00",
		"bazelgeuse" },
                { L"em118_05",
		"seething_bazelgeuse" },
                { L"em120_00",
		"tzitzi_ya_ku" },
                { L"em121_00",
		"behemoth" },
                { L"em122_00",
		"beotodus" },
                { L"em123_00",
		"banbaro" },
                { L"em124_00",
		"velkhana" },
                { L"em125_00",
		"namielle" },
                { L"em126_00",
		"shara_ishvalda" },
                { L"em127_00",
		"leshen" },
                { L"em127_01",
		"ancient_leshen" }
	};
}

#endif //_MHW_LOOKUP_MONSTER_H_

