#ifndef _MHW_LOOKUP_MONSTER_H_
#define _MHW_LOOKUP_MONSTER_H_

// list taken from https://github.com/sir-wilhelm/SmartHunter/blob/master/SmartHunter/Game/Config/MonsterDataConfig.cs
// cat tmp/SmartHunter/SmartHunter/Game/Config/MonsterDataConfig.cs | grep "\"em" -A1 -B0 | sed -e 's/\"em/{ L\"em/' -e 's/.*MONSTER.*/\L&/' 
// \ -e 's/.*monster.*",/& }/' -e 's/, }/ },/' -e 's/.*monster_/\t\t\"/' | grep -v -- "--"

namespace mhw_lookup {
	struct monster_data {
		const wchar_t	*id;
		const char	*name;
	};

	monster_data	MONSTERS[] = {
                { L"em001_00", // true
		"Rathian" },
                { L"em001_01", // true
		"Pink Rathian" },
                { L"em001_02", // true
		"Gold Rathian" },
                { L"em002_00", // true
		"Rathalos" },
                { L"em002_01", // true
		"Azure Rathalos" },
                { L"em002_02", // true
		"Silver Rathalos" },
                { L"em007_00", // true
		"Diablos" },
                { L"em007_01", // true
		"Black Diablos" },
                { L"em011_00", // true
		"Kirin" },
                { L"em018_00",
		"Yian Garuga" },
                { L"em018_05",
		"Scarred Yian Garuga" },
                { L"em023_00",
		"Rajang" },
                { L"em023_05",
		"Furious Rajang" },
                { L"em024_00",
		"Kushala Daora" },
                { L"em026_00",
		"Lunastra" },
                { L"em027_00",
		"Teostra" },
                { L"em032_00",
		"Tigrex" },
                { L"em032_01",
		"Brute Tigrex" },
                { L"em036_00",
		"Lavasioth" },
                { L"em037_00",
		"Nargacuga" },
                { L"em042_00",
		"Barioth" },
                { L"em043_00",
		"Deviljho" },
                { L"em043_05",
		"Savage Deviljho" },
                { L"em044_00",
		"Barroth" },
                { L"em045_00",
		"Uragaan" },
                { L"em057_00",
		"Zinogre" },
                { L"em063_00",
		"Brachydios" },
                { L"em063_05",
		"Raging Brachydios" },
                { L"em057_01",
		"Stygian Zinogre" },
                { L"em080_00",
		"Glavenus" },
                { L"em080_01",
		"Acidic Glavenus" },
                { L"em100_00",
		"Anjanath" },
                { L"em100_01",
		"Fulgur Anjanath" },
                { L"em101_00",
		"Great Jagras" },
                { L"em102_00",
		"Pukei Pukei" },
                { L"em102_01",
		"Coral Pukei Pukei" },
                { L"em103_00",
		"Nergigante" },
                { L"em103_05",
		"Ruiner Nergigante" },
                { L"em104_00",
		"Safi Jiiva" },
                { L"em105_00",
		"Xeno Jiiva" },
                { L"em106_00",
		"Zorah Magdaros" },
                { L"em107_00",
		"Kulu Ya Ku" },
                { L"em108_00",
		"Jyuratodus" },
                { L"em109_00",
		"Tobi Kadachi" },
                { L"em109_01",
		"Viper Tobi Kadachi" },
                { L"em110_00",
		"Paolumu" },
                { L"em110_01",
		"Nightshade Paolumu" },
                { L"em111_00",
		"Legiana" },
                { L"em111_05",
		"Shrieking Legiana" },
                { L"em112_00",
		"Great Girros" },
                { L"em113_00",
		"Odogaron" },
                { L"em113_01",
		"Ebony Odogaron" },
                { L"em114_00",
		"Radobaan" },
                { L"em115_00",
		"Vaal Hazak" },
                { L"em115_05",
		"Blackveil Vaal Hazak" },
                { L"em116_00",
		"Dodogama" },
                { L"em117_00",
		"Kulve Taroth" },
                { L"em118_00",
		"Bazelgeuse" },
                { L"em118_05",
		"Seething Bazelgeuse" },
                { L"em120_00",
		"Tzitzi Ya Ku" },
                { L"em121_00",
		"Behemoth" },
                { L"em122_00",
		"Beotodus" },
                { L"em123_00",
		"Banbaro" },
                { L"em124_00",
		"Velkhana" },
                { L"em125_00",
		"namielle" },
                { L"em126_00",
		"Shara Ishvalda" },
                { L"em127_00",
		"Leshen" },
                { L"em127_01",
		"Ancient Leshen" }
	};
}

#endif //_MHW_LOOKUP_MONSTER_H_

